// Generates lib/core/theme/app_tokens.dart from the canonical design-tokens.json
// (the same file the web app generates its CSS from). Run with:
//
//   dart run tool/gen_tokens.dart
//
// Edit colors in design-tokens.json, then re-run this AND the web generator
// (npm run gen:tokens) so both platforms stay in lockstep. Never hand-edit the
// generated app_tokens.dart.
import 'dart:convert';
import 'dart:io';

String _hexToColor(String hex) {
  final h = hex.replaceAll('#', '').toUpperCase();
  return 'Color(0xFF$h)';
}

void main() {
  final json = jsonDecode(File('design-tokens.json').readAsStringSync())
      as Map<String, dynamic>;
  final brand = json['brand'] as Map<String, dynamic>;
  final flavors = json['flavors'] as Map<String, dynamic>;
  final mascot = json['mascot'] as Map<String, dynamic>;

  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_tokens.dart from design-tokens.json — do not edit.')
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('/// Canonical PlayStudy brand, flavor, and mascot colors, shared')
    ..writeln('/// with the web app via design-tokens.json.')
    ..writeln('class AppTokens {')
    ..writeln('  AppTokens._();')
    ..writeln()
    ..writeln('  // Brand')
    ..writeln('  static const Color primary = ${_hexToColor(brand['primary']['hex'])};')
    ..writeln('  static const Color primaryDark = ${_hexToColor(brand['primaryDark']['hex'])};')
    ..writeln('  static const Color accent = ${_hexToColor(brand['accent']['hex'])};')
    ..writeln();

  b.writeln('  // Per-flavor primary / accent');
  flavors.forEach((name, f) {
    final cap = name[0].toUpperCase() + name.substring(1);
    b
      ..writeln('  static const Color ${name}Primary = ${_hexToColor(f['primary']['hex'])}; // $cap')
      ..writeln('  static const Color ${name}Accent = ${_hexToColor(f['accent']['hex'])};');
  });
  b.writeln();

  b.writeln('  // Pip mascot palette');
  mascot.forEach((k, v) {
    if (k.startsWith(r'$')) return;
    b.writeln('  static const Color pip${k[0].toUpperCase()}${k.substring(1)} = ${_hexToColor(v as String)};');
  });
  b.writeln('}');

  final out = File('lib/core/theme/app_tokens.dart');
  out.writeAsStringSync(b.toString());
  stdout.writeln('Wrote ${out.path}');
}
