// GENERATED by tool/gen_tokens.dart from design-tokens.json — do not edit.
import 'package:flutter/material.dart';

/// Canonical PlayStudy brand, flavor, and mascot colors, shared
/// with the web app via design-tokens.json.
class AppTokens {
  AppTokens._();

  // Brand
  static const Color primary = Color(0xFF6B5CE7);
  static const Color primaryDark = Color(0xFF8A7EFA);
  static const Color accent = Color(0xFFF7941D);

  // Per-flavor primary / accent
  static const Color focusPrimary = Color(0xFF6B5CE7); // Focus
  static const Color focusAccent = Color(0xFFF7941D);
  static const Color playfulPrimary = Color(0xFF7C5CFB); // Playful
  static const Color playfulAccent = Color(0xFFFB8A1C);
  static const Color proPrimary = Color(0xFF414BB4); // Pro
  static const Color proAccent = Color(0xFFBC7F38);
  static const Color rosePrimary = Color(0xFFEC4899); // Rose
  static const Color roseAccent = Color(0xFFA06CE4);

  // Pip mascot palette
  static const Color pipOrange = Color(0xFFF7941D);
  static const Color pipOrangeDark = Color(0xFFE07A12);
  static const Color pipOrangeLight = Color(0xFFFFB24D);
  static const Color pipCream = Color(0xFFFFFFFF);
  static const Color pipCreamShade = Color(0xFFE9ECF0);
  static const Color pipPaw = Color(0xFFDCE0E5);
  static const Color pipPawDark = Color(0xFFBFC5CC);
  static const Color pipInk = Color(0xFF1A1A1A);
}
